### ISSUE TITLE
superscripts in the yellow box (see entry 4.111 and email of Feb. 26)

### ISSUE THREAD

**Issue by peter9712** [BCDigSchol/census#100]
Entry 4.111 has a note with various Greek editions described with the standard superscripts--the yellow box doesn't render the superscripts. @Otterfan

**Comment by Otterfan** [comment]
Copying-and-pasting into the field preserved the superscripts for me. I've noticed that the source of the original text (PDF vs Word vs other text editors) can have an effect on what formatting carries over.

Regardless, I'm going to add a superscript style to the editor so we can fix future problems without re-pasting.
