### ISSUE TITLE
add Boolean search capabilities (in the simple search) 

### ISSUE THREAD

**Issue by peter9712** [BCDigSchol/census#113]
@Otterfan @jessemartinez

**Comment by peter9712** [comment]
make sure that the second term of a search "counts"! for instance, when we search "Cavafy cafe", only Cavafy seems to be taken into account

**Comment by Otterfan** [comment]
I've split this issue off into separate parts. We'll use this issue to track better support for boolean features (e.g. searches like `Cavafy OR Charalambidis`) and track the implied or (e.g. `Cavafy cafe`) in #124.

**Comment by annakijas1** [comment]
Boolean search has been addressed and discussed in greater length in issue #193. Closing this one.
