### ISSUE TITLE
search ALL fields (but not the yellow box itself) 

### ISSUE THREAD

**Issue by peter9712** [BCDigSchol/census#114]
@Otterfan @jessemartinez

**Comment by jessemartinez** [comment]
Just to clarify, you want to search through all 60+ fields in the Text record?

**Comment by peter9712** [comment]
At this point, yes, exactly, we were thinking that--but let's review/test this and see if it slows down searching, etc. @jessemartinez

**Comment by peter9712** [comment]
@jessemartinez @Otterfan -- The keyword search does not find Μαγδαληνή, which is the title of a collection! It appears in 4.140 and 4.145. Thus I assume that we are not yet able to search all the fields – I hope that we soon shall be. Won’t the advanced search page also change to allow searching in more fields than now?

**Comment by jessemartinez** [comment]
I haven't yet added additional fields to the search. I'm reviewing all the fields for inclusion and will update when this is ready.

**Comment by jessemartinez** [comment]
Please see issue #159.
