### ISSUE TITLE
in the browser view of results, text types should be reworded and should appear in a, b, c, d order each time, regardless of frequency

### ISSUE THREAD

**Issue by peter9712** [BCDigSchol/census#117]

**Comment by annakijas1** [comment]
It is standard for databases to return results and show items in limit sidebar by frequency and not alphabetical order. See for example this screenshot from the Ebsco Bibliography of Asian Studies database. 
![screen shot 2018-04-13 at 1 00 24 pm](https://user-images.githubusercontent.com/6841932/38747992-b1927f6c-3f1a-11e8-98e1-3a88c4458097.png)

**Comment by peter9712** [comment]
Agreed!
