### ISSUE TITLE
public: sorting results

### ISSUE THREAD

**Issue by peter9712** [BCDigSchol/census#126]
@Otterfan @jessemartinez -- we would like the ability, in the future, to sort the results not only by relevance, but also by chronology, topic author (and definitely a few other rankings TBA)

**Comment by Otterfan** [comment]
I've added basic sorting on date in 26fa48ff1c35f17148d67ddcfb0fe56b695b896a. It should be visible tonight.

**Comment by annakijas1** [comment]
You can sort by relevance, title, and date (oldest/newest). Within the results you can then use the filters on the left to narrow your results list, including by topic author, genre, etc.
