### ISSUE TITLE
Format of 'tombstone' for journals 

### ISSUE THREAD

**Issue by peter9712** [BCDigSchol/census#137]
The format for journals should include: the
issue number in full and out of parentheses; full dates within parentheses; just like the yellow
box. 
For instance: A search for “Cavafy Haas” does bring up the Grand Street entry in which she (=Diana Haas)
is a translator, as ‘Grand Street’. But the result should state “Grand Street 2.3 (Spring 1983)” in
the ‘tombstone'

(Also: all issue numbers that contain a period do not come over well in the left column)

**Comment by Otterfan** [comment]
I *think* we accomplished most of this with a commit last week (65a1bec), but I'm going to keep this open until I feel more sure about it.

**Comment by Otterfan** [comment]
We have a new commit today (464fdb0) that should fix the display issues except for the page numbers.

As Anna mentions, the page numbers in journal entries come from the _text_ page numbers, not the _component_ page numbers. Adding component page numbers to match the search string would be possible, but it would require a bit of work.

If we still want to see component page numbers in these entries, we should create a new dedicated issue.
