### ISSUE TITLE
When searching for a component or for a title string that is within a (usually long) title that contains one or more pipes:

### ISSUE THREAD

**Issue by peter9712** [BCDigSchol/census#143]
In the results, it seems best to have the entire series listed only in Line 3 of the 'tombstone'. Line 1 could give the
title of the particular searched-for item within the stream of pipes, perhaps with a series of dots
before and after (e.g. “Ithaca”…). E.g. “Ithaca” at 4.524 or 4.479.

**Comment by annakijas1** [comment]
See #156

**Comment by annakijas1** [comment]
See more recent requests #196, #195 #194, #188.
