### ISSUE TITLE
terms glossed when user hovers over them 

### ISSUE THREAD

**Issue by peter9712** [BCDigSchol/census#148]
(like 'component')

**Comment by peter9712** [comment]
or, perhaps, we can add an 'i' (in a circle; next to the term) that will provide information when hovered over/clicked.

**Comment by annakijas1** [comment]
Information about terms used in the database and other user documentation can be provided in a user guide section.

**Comment by GreekCommons** [comment]
@Otterfan @jessemartinez @peter9712 
It would be much more technologically 'refined' to have the information on terms (their glossing) available locally, via an 'i'. (A user guide may be long to search, and users may not bother to read it.)
