### ISSUE TITLE
a suggestion for the record (appearance/what fields it includes) for a study within a volume 

### ISSUE THREAD

**Issue by peter9712** [BCDigSchol/census#157]
@Otterfan @jessemartinez 

The record should read (on the left) (adding in the author’s name and the title of the volume, also changing/shifting a few facts):
Title: "Homer and the Greek Civil War, 1946-1949"
Author: Ricks, David
In: Homer in the Twentieth Century
Date of publication: 2007
Pages: 231-244
Place of publication: Oxford
Publisher: Oxford University Press
(Note: For all studies we should give in the record’s fields the name of the author and the title of the volume or the journal title and the date!)

**Comment by annakijas1** [comment]
"In: Homer in the Twentieth Century" is being pulled from the Volume module;
Remove the "pp." that appears before page range in the "Page count" field.

**Comment by annakijas1** [comment]
View more recent request in #194
