### ISSUE TITLE
computation of relevance? 

### ISSUE THREAD

**Issue by peter9712** [BCDigSchol/census#159]
in search results, how is relevance being determined? What weight is currently being given to what fields? Do you have a 'list' to send to us at this point? That would be helpful in our (re?) ranking of fields that you requested of us.

**Comment by jessemartinez** [comment]
Here is the updated list of search fields based on commit 9e94b142353984da867164b29604674a82cf80e6

The larger the weight/boost the more that field's matching will get boosted in the results. (NB The order of the fields in this list is unimportant.)

Feel free to propose different weights/boosts to these fields. It can be any value including decimals. In my naive sample below, I have `name` fields boosted twice as much as `title` fields, which is also 5 times boosted than all other fields. 

Field name | weight/boost | English stemming | Greek stemming
------------ | ------------- | ------------- | -------------
topic_author.full_name | 10 | :white_check_mark: | :white_check_mark:
topic_author.alternate_name | 10 | :white_check_mark: | :white_check_mark:
text_citations.name | 10 | :white_check_mark: | :white_check_mark:
components.component_citations.name | 10 | :white_check_mark: | :white_check_mark:
title | 5 | :white_check_mark: | :white_check_mark:
components.title | 5 | :white_check_mark: | :white_check_mark:
components.genre |  |  | 
components.text_type |  |  | 
components.collection |  | :white_check_mark: | :white_check_mark:
components.note |  | :white_check_mark: | :white_check_mark:
text_type |  |  | 
sort_date |  |  | 
original_greek_title |  | :white_check_mark: | :white_check_mark:
genre |  |  | 
publication_places.place.name |  | :white_check_mark: | :white_check_mark:
publisher |  | :white_check_mark: | :white_check_mark:
journal.title |  | :white_check_mark: | :white_check_mark:
material_type |  |  | 
other_text_languages.language.name |  | :white_check_mark: | 
source |  | :white_check_mark: | :white_check_mark:
note |  | :white_check_mark: | :white_check_mark:
census_id |  |  | 
series |  | :white_check_mark: | :white_check_mark:
original_greek_place_of_publication |  |  | :white_check_mark:
original_greek_publisher |  |  | :white_check_mark:
original_greek_date |  |  | 
sponsoring_organization |  | :white_check_mark: | :white_check_mark:
special_location_of_item |  |  | 
special_source_of_info |  | :white_check_mark: | :white_check_mark:
issue_editor |  |  | :white_check_mark:
issue_title |  |  | :white_check_mark:
abstract |  |  | :white_check_mark:
authors_name_from_source |  |  | :white_check_mark:
editorial_annotation |  | :white_check_mark: | :white_check_mark:
original_greek_collection |  |  | :white_check_mark:
collection |  |  | :white_check_mark:
volumes.title |  | :white_check_mark: | :white_check_mark:
standard_numbers.value |  |  |
