### ISSUE TITLE
is there a way for us to see/receive reports of what users search for? 

### ISSUE THREAD

**Issue by peter9712** [BCDigSchol/census#174]
@jessemartinez @Otterfan @GreekCommons

**Comment by Otterfan** [comment]
We'll be adding Google Analytics to the site, which will keep track of search queries, traffic, and frequently-accessed pages and records.

**Comment by annakijas1** [comment]
We will not be storing user search histories or data due to privacy/security issues.

**Comment by GreekCommons** [comment]
Is the concern for our privacy or security (the database's or BC's) or for that of the users? We believe that numerous websites collects such info on their users.
