### ISSUE TITLE
Collections into the UI

### ISSUE THREAD

**Issue by GreekCommons** [BCDigSchol/census#176]
@Otterfan @jessemartinez @peter9712 
(The titles of) ‘Collections’ have been lost in the interface and should be searchable, and then retrieved/displayed. We have a specific database-field for them with each component. 
     Unfortunately we do not have a field for them in the main entry (so we have sometimes mentioned the title of such a collection in a – more general -- Note field).

**Comment by GreekCommons** [comment]
Please note that Greek titles for collections are now being added (main entry and components). Usually in this format: From _English collection title [Greek collection title]_.

**Comment by annakijas1** [comment]
Collection titles need to be entered in the "collection" field of a Text record. If they are not there, see for example 4.688, then they will not be searchable by the "collection" field in the advanced search.
