### ISSUE TITLE
Move entry number up higher in results

### ISSUE THREAD

**Issue by GreekCommons** [BCDigSchol/census#178]
@Otterfan @jessemartinez @peter9712 

Seeing the entry number now in the results is very welcome. Thank you!
Still, in the individual records it is often appearing so low down the left column as to be cumbersome. How about moving it up?

**Comment by jessemartinez** [comment]
Certainly! Could you provide a location for the entry number relative to the other fields? An explicit description of the locations of fields in the text record  would be helpful.

**Comment by annakijas1** [comment]
@peter9712 If you have an idea of the order in which you'd like the fields to appear in the public record, please let us know. Prioritize what should appear above the fold and then below that someone will need to scroll down to view.

**Comment by annakijas1** [comment]
Closing this issue. See #196, #195, #194 for most recent UI requests, including order of fields.
