### ISSUE TITLE
Link alternate spellings of names/alternate names

### ISSUE THREAD

**Issue by Otterfan** [BCDigSchol/census#179]
E.g. 'Konstantin Kavafis', 'K.P. Kavafis', etc. should be linkable from Cavafy. This will most likely require a new database table built from the "people" table as well as possibly content from the VIAF, etc. data.

**Comment by GreekCommons** [comment]
@Otterfan @jessemartinez @peter9712 
A request that the linking of the variant spellings of each Greek creative author's name to his/her Topic header name will include also the Greek form of his name (and in the future, the LOC authority form as well).

**Comment by annakijas1** [comment]
When the hyperlink is turned on for the author listed in a record, a user will be taken to the related record in the author table where they will see all of the data that has been compiled for that author. @Otterfan Would that be sufficient?

**Comment by GreekCommons** [comment]
Are we now combining into a single field all (!) the alternate names of authors: not keeping a separate field for their 'alternate' name (e.g. the maiden name or pseudonym) and a separate field for all the variant spellings of the author heading form?

**Comment by annakijas1** [comment]
Alternate names will be split up to reflect those entered in by team vs. what is pulled from VIAF. Alternate names can be searched and found now.
