### ISSUE TITLE
browsing volumes (in public view)

### ISSUE THREAD

**Issue by peter9712** [BCDigSchol/census#183]
@Otterfan @jessemartinez @GreekCommons

the order in the public view of volumes is a bit off. Especially because, for instance, the article "A" is being 'counted' when it's at the beginning of a volume's title. 

Also, for instance, "Greece and Britain since 1945" appears before "Greece: A Traveler's Literary Companion".

**Comment by jessemartinez** [comment]
The next push to production should fix the sorting issue.
