### ISSUE TITLE
in browsing, for the authors tab (in the public view): 

### ISSUE THREAD

**Issue by peter9712** [BCDigSchol/census#184]
all titles mentioned under each author should have a publication year within parentheses at their end.

**Comment by GreekCommons** [comment]
If this is difficult to do for each title in browsing, let's at least add the author's dates to the Authors tab in 'public'.

**Comment by annakijas1** [comment]
Ben has updated the view in the author page.

**Comment by peter9712** [comment]
@annakijas1 @Otterfan Will this (the addition of publication year with parentheses) be visible after tonight's deployment? I don't see it yet in the public view.
