### ISSUE TITLE
Original Greek title(s) and year(s) in the display (expanded record)

### ISSUE THREAD

**Issue by GreekCommons** [BCDigSchol/census#199]
@Otterfan @jessemartinez @peter9712 @annakijas1 
The original Greek title should be added as a field in the expanded record display! (Preferably its year of publication too.)  Users may well want to search by the Greek title, to see if it has been translated into English, and/or to find the title in English that translators have given to a Greek work. 
     (Additionally, we know that visualization will eventually include a comparison between the year of original Greek publication and the year of translation into English.)
  (These fields were included in the 'Relevance' (and inclusion) tables that Peter and I submitted -- cf. GH 159) .

**Comment by annakijas1** [comment]
This was unclear in issue #159, because that issue was specific to relevancy ranking, not the UI expanded record display.

**Comment by annakijas1** [comment]
Original Greek Title will be visible in the expanded record.
