### ISSUE TITLE
Fields not saving changes

### ISSUE THREAD

**Issue by annakijas1** [BCDigSchol/census#51]
1. "names" field under "Citations" 
2. "from language" to "to language" under "Citations"
3. "language" (drop-down) under "Other languages in text"

In Authors table - all of the fields retain changes except for "domicile"

**Comment by Otterfan** [comment]
I'm probably going to disable this and then re-enable it when it's working (hopefully today!).

**Comment by Otterfan** [comment]
Language drop-down fixed in #23.

**Comment by Otterfan** [comment]
Names fields fixed in #52. Only citation languages left...

**Comment by Otterfan** [comment]
Domicile still doesn't save!
