### ISSUE TITLE
Add prev/next in entry form

### ISSUE THREAD

**Issue by annakijas1** [BCDigSchol/census#55]
Can a prev/next button be added in the entry forms to move to the next or past entry instead of returning to the full list?

**Comment by Otterfan** [comment]
Just to clarify, this will save _and_ move on to the next/prev entry?

**Comment by annakijas1** [comment]
I would think that it would just move prev/next. You would still have to save the changes manually.

**Comment by annakijas1** [comment]
Also, when saving the page - do not throw back to homepage, but stay within the same result range as the entry you edited.
