### ISSUE TITLE
Enable components boxes to be re-ordered

### ISSUE THREAD

**Issue by annakijas1** [BCDigSchol/census#72]
Can components boxes be re-ordered during edits in order to place in the order in which they appear in the entry?

**Comment by Otterfan** [comment]
There's a problem with saving!

**Comment by Otterfan** [comment]
Doesn't seem to be working in production...

**Comment by Otterfan** [comment]
Fixed as a side effect of 3851dc6aa37104a1cf26c84f414f4601beedfc9f
