### ISSUE TITLE
improve our facility in erasing/deleting in all fields 

### ISSUE THREAD

**Issue by peter9712** [BCDigSchol/census#87]
Seee GD III.1.

**Comment by Otterfan** [comment]
Hi Peter, has this improved at all? I think it had to do with how sorting and ordering was implemented before, and it's improved on my end since we made some fixes to sorting. Do you still see the same problems?

**Comment by annakijas1** [comment]
@peter9712 @Otterfan All fields allow you to highlight a word or value by clicking on it or dragging the mouse over the entire word/value to highlight. The only place where you can not quickly drag the mouse to highlight is in the Citations section.

**Comment by annakijas1** [comment]
Some of this may be related to the browser bug, noted in #58
